package edu.sru.MusicLibrary.util.enums;

public enum Role {

	ROLE_USER, ROLE_ADMIN, ROLE_ADMIN_SHADOW, ROLE_HELPDESK_ADMIN, ROLE_HELPDESK_REGULAR, ROLE_TECHNICALSERVICE,
	ROLE_SECURITY, ROLE_CUSTOMERSERVICE, ROLE_SALES, ROLE_HIRINGMANAGER,
}
